### ISSUE TITLE
what version of windows is this driver for?

### ISSUE THREAD

**Issue by leandrofreirex** [zagdrath/HP-NC550SFP-Drivers#1]
I'm installing on version 2022 and it's crashing the system, just out of curiosity.

**Comment by zagdrath** [comment]
These have worked for me on Windows 10, 11, and Server 2022 so far.

**Comment by leandrofreirex** [comment]
I managed to install it, after testing many versions of systems, it finally worked when I was about to give up, I think because of my hardware.
In the last attempt, I installed the driver it froze the system, it gave a blue screen and restarted, in the attempt to boot again it froze at boot then I gave up and went to do other things, when I came back it had started normally, however in the device manager it has 8 ports, two of which are active and apparently working and the rest with the status disconnected, which makes me sad since the card only has two sfp+ ports.
I'm using build 1006 sep 2022 from server 2022

**Comment by zagdrath** [comment]
I have had that issue where more than one port shows up in Device Manager but that has not caused any issues that I am am aware of. You could try downloading the driver from HPE and unzipping the .exe and installing that .inf manually. It states it's for Windows Server 2003 x64 editions but it has worked on modern versions for me so i'm not exactly sure what the issue you are having is.

[https://support.hpe.com/connect/s/softwaredetails?language=en_US&softwareId=MTX_d0af1b746aa248f1963f34a676](https://support.hpe.com/connect/s/softwaredetails?language=en_US&softwareId=MTX_d0af1b746aa248f1963f34a676)
